# Generated by Django 5.1.15 on 2026-08-12 19:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_options_alter_usagelog_options_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operatorinvite',
            options={'verbose_name': 'Invitación de operador', 'verbose_name_plural': 'Invitaciones de operador'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='operatorinvite',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_invites', to='companies.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='operatorinvite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='operatorinvite',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Vence el'),
        ),
        migrations.AlterField(
            model_name='operatorinvite',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Usada'),
        ),
        migrations.AlterField(
            model_name='operatorinvite',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='companies.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin de empresa'), ('operator', 'Operador')], max_length=20, verbose_name='Rol'),
        ),
    ]
