# Generated by Django 5.1.15 on 2026-08-10 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='shipment_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='shipments.shipmentitem'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='dispute_reason',
            field=models.TextField(blank=True),
        ),
    ]
