# Generated by Django 5.1.15 on 2026-08-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_evidence_shipment_item_shipment_dispute_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='auto_closed',
            field=models.BooleanField(default=False),
        ),
    ]
