# Generated by Django 5.1.15 on 2026-08-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_shipment_auto_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
