# Generated by Django 5.1.15 on 2026-08-12 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_options_alter_product_barcode_and_more'),
        ('companies', '0003_alter_company_options_alter_usagelog_options_and_more'),
        ('shipments', '0004_shipment_reminder_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evidence',
            options={'verbose_name': 'Evidencia', 'verbose_name_plural': 'Evidencia'},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'verbose_name': 'Remito', 'verbose_name_plural': 'Remitos'},
        ),
        migrations.AlterModelOptions(
            name='shipmentitem',
            options={'verbose_name': 'Ítem del remito', 'verbose_name_plural': 'Ítems del remito'},
        ),
        migrations.AlterField(
            model_name='evidence',
            name='file_url',
            field=models.URLField(max_length=1000, verbose_name='URL de la foto'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='shipments.shipment', verbose_name='Remito'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='shipment_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='shipments.shipmentitem', verbose_name='Ítem del remito'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='type',
            field=models.CharField(choices=[('dispatch', 'Despacho'), ('reception', 'Recepción')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to=settings.AUTH_USER_MODEL, verbose_name='Subida por'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='auto_closed',
            field=models.BooleanField(default=False, verbose_name='Cerrado automáticamente'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='companies.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Despachado el'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='dispute_reason',
            field=models.TextField(blank=True, verbose_name='Motivo de la queja'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='link_opened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Link abierto por el receptor el'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to=settings.AUTH_USER_MODEL, verbose_name='Operador'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='public_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='Token del link público'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='receiver_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email del receptor'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='receiver_name',
            field=models.CharField(max_length=255, verbose_name='Receptor'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfono del receptor'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Recordatorio enviado el'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='response_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Plazo de respuesta'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('dispatched', 'Despachado'), ('accepted', 'Aceptado'), ('disputed', 'En disputa'), ('closed', 'Cerrado')], default='draft', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_items', to='catalog.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipments.shipment', verbose_name='Remito'),
        ),
    ]
