# Generated by Django 5.1.15 on 2026-08-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_alter_evidence_options_alter_shipment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='file_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, verbose_name='Hash SHA-256'),
        ),
    ]
