# Generated by Django 5.1.15 on 2026-08-17 18:46

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_options_alter_product_barcode_and_more'),
        ('companies', '0004_historicalcompany'),
        ('shipments', '0006_evidence_file_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEvidence',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('type', models.CharField(choices=[('dispatch', 'Despacho'), ('reception', 'Recepción')], max_length=20, verbose_name='Tipo')),
                ('file_url', models.URLField(max_length=1000, verbose_name='URL de la foto')),
                ('file_hash', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Hash SHA-256')),
                ('uploaded_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de subida')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shipments.shipment', verbose_name='Remito')),
                ('shipment_item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shipments.shipmentitem', verbose_name='Ítem del remito')),
                ('uploaded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Subida por')),
            ],
            options={
                'verbose_name': 'historial de evidencia',
                'verbose_name_plural': 'historial de evidencia',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalShipment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=255, verbose_name='Receptor')),
                ('receiver_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del receptor')),
                ('receiver_phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono del receptor')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('dispatched', 'Despachado'), ('accepted', 'Aceptado'), ('disputed', 'En disputa'), ('closed', 'Cerrado')], default='draft', max_length=20, verbose_name='Estado')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True, verbose_name='Despachado el')),
                ('public_token', models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name='Token del link público')),
                ('link_opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Link abierto por el receptor el')),
                ('response_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Plazo de respuesta')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('dispute_reason', models.TextField(blank=True, verbose_name='Motivo de la queja')),
                ('auto_closed', models.BooleanField(default=False, verbose_name='Cerrado automáticamente')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Recordatorio enviado el')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='companies.company', verbose_name='Empresa')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'historial de remito',
                'verbose_name_plural': 'historial de remitos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalShipmentItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.product', verbose_name='Producto')),
                ('shipment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shipments.shipment', verbose_name='Remito')),
            ],
            options={
                'verbose_name': 'historial de ítem del remito',
                'verbose_name_plural': 'historial de ítems del remito',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
