# Generated by Django 5.1.15 on 2026-08-09 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('shipments_created', models.IntegerField(default=0)),
                ('photos_uploaded', models.IntegerField(default=0)),
                ('emails_sent', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='companies.company')),
            ],
            options={
                'unique_together': {('company', 'month')},
            },
        ),
    ]
