# Generated by Django 5.1.15 on 2026-08-12 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_usagelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='usagelog',
            options={'verbose_name': 'Consumo mensual', 'verbose_name_plural': 'Consumo mensual'},
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='company',
            name='plan',
            field=models.CharField(blank=True, max_length=50, verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='company',
            name='trial_shipments_remaining',
            field=models.IntegerField(default=10, verbose_name='Remitos de trial restantes'),
        ),
        migrations.AlterField(
            model_name='usagelog',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='companies.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='usagelog',
            name='emails_sent',
            field=models.IntegerField(default=0, verbose_name='Emails enviados'),
        ),
        migrations.AlterField(
            model_name='usagelog',
            name='month',
            field=models.CharField(max_length=7, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='usagelog',
            name='photos_uploaded',
            field=models.IntegerField(default=0, verbose_name='Fotos subidas'),
        ),
        migrations.AlterField(
            model_name='usagelog',
            name='shipments_created',
            field=models.IntegerField(default=0, verbose_name='Remitos creados'),
        ),
    ]
