# Generated by Django 5.1.15 on 2026-08-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_historicalcompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo la empresa aceptó los Términos de Servicio. Se carga a mano al cerrar el contrato; vacío = todavía no aceptó.', null=True, verbose_name='Aceptación de los Términos'),
        ),
        migrations.AddField(
            model_name='company',
            name='terms_accepted_version',
            field=models.CharField(blank=True, help_text='Qué versión del texto legal aceptó, p. ej. «v1».', max_length=20, verbose_name='Versión aceptada'),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo la empresa aceptó los Términos de Servicio. Se carga a mano al cerrar el contrato; vacío = todavía no aceptó.', null=True, verbose_name='Aceptación de los Términos'),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='terms_accepted_version',
            field=models.CharField(blank=True, help_text='Qué versión del texto legal aceptó, p. ej. «v1».', max_length=20, verbose_name='Versión aceptada'),
        ),
    ]
